# Generated by Django 3.2.6 on 2021-09-05 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
        ('djangoTags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='products',
            field=models.ManyToManyField(to='Products.Product'),
        ),
    ]
