# Generated by Django 3.2.6 on 2021-09-05 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
        ('djangoTags', '0002_tag_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='products',
            field=models.ManyToManyField(blank=True, to='Products.Product'),
        ),
    ]
