# Generated by Django 3.2.6 on 2021-09-09 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoCategory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
