# Generated by Django 3.2.6 on 2021-09-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoCategory', '0001_initial'),
        ('Products', '0002_product_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, to='djangoCategory.Categories'),
        ),
    ]
