# Generated by Django 3.2.6 on 2021-09-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name_plural': 'Galleries'},
        ),
        migrations.AddField(
            model_name='product',
            name='ad_in_home',
            field=models.BooleanField(default=False),
        ),
    ]
